apiVersion: v1
kind: Service
metadata:
  name: posts-srv
spec:
  type: NodePort
  selector:
    app: posts
  ports:
    - name: posts
      port: 4000 #Node port service has a port of its own
      protocol: TCP
      targetPort: 4000 #port for the pod attached to a container ultimate endpoint